<?xml version="1.0"?>
<!-- Dual camera differential drive robot for Gazebo -->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="dual_camera_bot">
  <xacro:property name="pi" value="3.1415926535897931"/>
  <xacro:property name="wheel_radius" value="0.08"/>
  <xacro:property name="wheel_separation" value="0.45"/>
  <xacro:property name="base_mass" value="15.0"/>
  <xacro:property name="wheel_mass" value="1.0"/>

  <link name="base_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${base_mass}"/>
      <inertia ixx="1.0" ixy="0" ixz="0" iyy="1.0" iyz="0" izz="1.0"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0.1" rpy="0 0 0"/>
      <geometry>
        <box size="0.6 0.4 0.2"/>
      </geometry>
      <material name="chassis_green">
        <color rgba="0.2 0.6 0.2 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0.1" rpy="0 0 0"/>
      <geometry>
        <box size="0.6 0.4 0.2"/>
      </geometry>
    </collision>
  </link>

  <link name="left_wheel_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${wheel_mass}"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.005"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder length="0.06" radius="${wheel_radius}"/>
      </geometry>
      <material name="wheel_black">
        <color rgba="0.1 0.1 0.1 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder length="0.06" radius="${wheel_radius}"/>
      </geometry>
    </collision>
  </link>

  <link name="right_wheel_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${wheel_mass}"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.005"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder length="0.06" radius="${wheel_radius}"/>
      </geometry>
      <material name="wheel_black">
        <color rgba="0.1 0.1 0.1 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder length="0.06" radius="${wheel_radius}"/>
      </geometry>
    </collision>
  </link>

  <joint name="left_wheel_joint" type="continuous">
    <origin xyz="0 ${wheel_separation/2} 0.08" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="left_wheel_link"/>
    <axis xyz="0 1 0"/>
    <limit effort="15" velocity="10"/>
  </joint>

  <joint name="right_wheel_joint" type="continuous">
    <origin xyz="0 -${wheel_separation/2} 0.08" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="right_wheel_link"/>
    <axis xyz="0 1 0"/>
    <limit effort="15" velocity="10"/>
  </joint>

  <link name="caster_link">
    <visual>
      <origin xyz="-0.25 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="0.05"/>
      </geometry>
      <material name="caster_grey">
        <color rgba="0.5 0.5 0.5 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="-0.25 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="0.05"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="-0.25 0 0" rpy="0 0 0"/>
      <mass value="0.5"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
  </link>

  <joint name="caster_joint" type="fixed">
    <origin xyz="-0.25 0 -0.02" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="caster_link"/>
  </joint>

  <link name="rgb_camera_link">
    <visual>
      <origin xyz="0.25 0 0.25" rpy="0 0 0"/>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
      <material name="rgb_camera_body">
        <color rgba="0.2 0.2 0.2 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0.25 0 0.25" rpy="0 0 0"/>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0.25 0 0.25" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="rgb_camera_joint" type="fixed">
    <origin xyz="0.25 0 0.2" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="rgb_camera_link"/>
  </joint>

  <link name="panorama_camera_link">
    <visual>
      <origin xyz="0 0 0.35" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.04" length="0.08"/>
      </geometry>
      <material name="panorama_body">
        <color rgba="0.15 0.15 0.15 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0.35" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.04" length="0.08"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0.35" rpy="0 0 0"/>
      <mass value="0.12"/>
      <inertia ixx="0.0002" ixy="0" ixz="0" iyy="0.0002" iyz="0" izz="0.0002"/>
    </inertial>
  </link>

  <joint name="panorama_camera_joint" type="fixed">
    <origin xyz="0 0 0.3" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="panorama_camera_link"/>
  </joint>

  <transmission name="left_wheel_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <actuator name="left_wheel_motor">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
    <joint name="left_wheel_joint">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
  </transmission>

  <transmission name="right_wheel_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <actuator name="right_wheel_motor">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
    <joint name="right_wheel_joint">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
  </transmission>

  <gazebo>
    <plugin name="diff_drive" filename="libgazebo_ros_diff_drive.so">
      <ros>
        <namespace>/dual_camera_bot</namespace>
        <remapping>cmd_vel:=cmd_vel</remapping>
        <remapping>odom:=odom</remapping>
      </ros>
      <update_rate>60</update_rate>
      <left_joint>left_wheel_joint</left_joint>
      <right_joint>right_wheel_joint</right_joint>
      <wheel_separation>${wheel_separation}</wheel_separation>
      <wheel_diameter>${2 * wheel_radius}</wheel_diameter>
      <cmd_vel_topic>cmd_vel</cmd_vel_topic>
      <odom_topic>odom</odom_topic>
      <odom_frame>odom</odom_frame>
      <robot_base_frame>base_link</robot_base_frame>
      <publish_tf>true</publish_tf>
      <publish_odom>true</publish_odom>
    </plugin>
  </gazebo>

  <gazebo reference="left_wheel_link">
    <mu1>10</mu1>
    <mu2>10</mu2>
    <kp>100000.0</kp>
    <kd>1.0</kd>
  </gazebo>

  <gazebo reference="right_wheel_link">
    <mu1>10</mu1>
    <mu2>10</mu2>
    <kp>100000.0</kp>
    <kd>1.0</kd>
  </gazebo>

  <gazebo reference="rgb_camera_link">
    <sensor name="rgb_camera" type="camera">
      <always_on>true</always_on>
      <update_rate>30</update_rate>
      <visualize>true</visualize>
      <camera>
        <horizontal_fov>1.047</horizontal_fov>
        <image>
          <width>1280</width>
          <height>720</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.05</near>
          <far>20</far>
        </clip>
      </camera>
      <plugin name="rgb_camera_controller" filename="libgazebo_ros_camera.so">
        <ros>
          <namespace>/dual_camera_bot</namespace>
          <remapping>image:=rgb/image_raw</remapping>
          <remapping>camera_info:=rgb/camera_info</remapping>
        </ros>
        <camera_name>rgb</camera_name>
        <frame_name>rgb_camera_link</frame_name>
      </plugin>
    </sensor>
  </gazebo>

  <gazebo reference="panorama_camera_link">
    <sensor name="panorama_camera" type="camera">
      <always_on>true</always_on>
      <update_rate>15</update_rate>
      <visualize>true</visualize>
      <camera>
        <horizontal_fov>6.28318530718</horizontal_fov>
        <image>
          <width>2048</width>
          <height>1024</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.05</near>
          <far>50</far>
        </clip>
        <distortion>
          <k1>0.0</k1>
          <k2>0.0</k2>
          <k3>0.0</k3>
          <p1>0.0</p1>
          <p2>0.0</p2>
        </distortion>
      </camera>
      <plugin name="panorama_camera_controller" filename="libgazebo_ros_fisheye_camera.so">
        <ros>
          <namespace>/dual_camera_bot</namespace>
          <remapping>image:=panorama/image_raw</remapping>
          <remapping>camera_info:=panorama/camera_info</remapping>
        </ros>
        <camera_name>panorama</camera_name>
        <frame_name>panorama_camera_link</frame_name>
      </plugin>
    </sensor>
  </gazebo>
</robot>
